# Generated by Django 3.1.7 on 2021-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0002_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(default='Unranked', max_length=30),
        ),
    ]
