# Generated by Django 3.1.7 on 2021-04-13 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0003_auto_20210413_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rewards',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
