# Generated by Django 3.1.7 on 2021-04-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0004_auto_20210413_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_nm',
            field=models.CharField(default='Exergam', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='last_nm',
            field=models.CharField(default='exergam_user', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='usernm',
            field=models.CharField(default='exergam_user', max_length=40),
        ),
    ]
