# Generated by Django 3.1.7 on 2021-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0005_auto_20210414_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_nm',
            field=models.CharField(default='User', max_length=40),
        ),
    ]
