# Generated by Django 3.1.7 on 2021-04-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0006_auto_20210414_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
