# Generated by Django 3.1.7 on 2021-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0007_auto_20210417_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usernm',
            field=models.CharField(default='<django.db.models.fields.EmailField>', max_length=40),
        ),
    ]
