# Generated by Django 3.1.7 on 2021-04-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0007_auto_20210417_0103'),
        ('exergam', '0009_auto_20210417_1416'),
    ]

    operations = [
    ]
