# Generated by Django 3.1.7 on 2021-04-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0010_merge_20210417_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usernm',
            field=models.CharField(default='exergam_user', max_length=40),
        ),
    ]
