# Generated by Django 3.1.7 on 2021-04-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0012_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../images/login.jpg', upload_to=''),
        ),
    ]
