# Generated by Django 3.1.7 on 2021-04-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0013_auto_20210418_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../../static/exergam/images/login.jpg', upload_to=''),
        ),
    ]
