# Generated by Django 3.1.7 on 2021-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0014_auto_20210424_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='../../static/exergam/images/login.jpeg', upload_to=''),
        ),
    ]
