# Generated by Django 3.1.7 on 2021-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exergam', '0015_auto_20210424_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(choices=[('../images/login.jpeg', 'Default'), ('../images/1.jpg', '1'), ('../images/2.jpg', '2'), ('../images/3.jpg', '3'), ('../images/4.jpg', '4'), ('../images/5.jpg', '5'), ('../images/6.jpg', '6'), ('../images/7.jpg', '7'), ('../images/8.jpg', '8'), ('../images/9.jpg', '9'), ('../images/10.jpg', '10'), ('../images/12.jpg', '12'), ('../images/13.jpg', '13'), ('../images/14.jpg', '14'), ('../images/15.jpg', '15'), ('../images/16.jpg', '16'), ('../images/17.jpg', '17'), ('../images/18.jpg', '18'), ('../images/19.jpg', '19'), ('../images/20.jpg', '20')], default='../images/login.jpeg', upload_to=''),
        ),
    ]
