"""
Django settings for projectb14 project.
Generated by 'django-admin startproject' using Django 3.1.6.
For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import django_heroku
import sys
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#import upstream as upstream

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '64(!cj!!8p84ma1hxgi(jt2^yu5%hou)zia6%2gpzyx9bq!*@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'exergam.apps.ExergamConfig', #include the app
    'allauth', #installed following django allauth import
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projectb14.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projectb14.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        # this is for local usage, this won't work with heroku
        #   'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #   'NAME': 'andrewexergam1',
        #   'USER': 'postgres',
        #   'PASSWORD': 'uniforms2',
        #   'HOST': '',
        #   'PORT': '5432',
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
         #'NAME': 'projb14',
         #'USER': 'postgres',
         #'PASSWORD': 'projectb14',
         #'HOST': '',
         #'PORT': '5432',
        #For Heroku
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd816quvns8hbdh',
        'USER': 'hkcinvbnscuufs',
        'PASSWORD': '31213a63b9e8e5e5e091aa0ba0844bc33eea7014c010e4c874ef7beb5ed3b58f',
        'HOST': 'ec2-54-205-183-19.compute-1.amazonaws.com',
        'PORT': '5432'
        #JJ
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }

# TEST_DATABASES = {
#     'default': dj_database_url.config(env='TEST_DATABASE_URL')
# }

# TEST_RUNNER = 'exergam.test_suite_runner.HerokuTestSuiteRunner'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/')
]
MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'images')
MEDIAFILES_DIRS = [
    os.path.join(BASE_DIR, 'images'),
]
django_heroku.settings(locals(), test_runner=False)


#Google Authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

AUTH_USER_MODEL = 'exergam.User'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            #For Heroku App
            'client_id': '1083374100145-ie8a9njva588r8n5qdcpfbbglha8o5ne.apps.googleusercontent.com',
            'secret': 'eq98hXtUNB47neFl2v8QRNTn',
            'key':'',
            #Andrew Local
            #'client_id': '892017048719-2fj3ma253sbp5vikph0a7el826bgajtr.apps.googleusercontent.com',
            #'secret': 'aOuqm_tFHeiWd3xdfB9qkQYP',
            #'key':'',
        }
    }
}

SITE_ID = 4 #For Heroku Deployment, SiteID should be 4

LOGIN_REDIRECT_URL = '/exergam/'
LOGOUT_REDIRECT_URL = '/'
